#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  1 22:59:54 2020

@author: stepianno
"""

import re

def pass_check(amount, l, password):
    ran = re.findall('\d+', amount)
    low = int(ran[0])
    high = int(ran[1])
    times = len(re.findall(l, password))
    if times >= low and times <= high:
        return True
    else:
        return False
    
def count_check(pass_list):
    count = 0
    for line in pass_list:
        amount, l, password = line.split()
        if pass_check(amount, l[0], password):
            count += 1
    return count

def new_pass_check(loc, l, password):
    ran = re.findall('\d+', loc)
    low = int(ran[0]) - 1
    high = int(ran[1]) - 1
    try:
        a = password[low]
    except:
        a = 'none'
    try:
        b = password[high]
    except:
        b = 'none'
    if a == b:
        return False
    elif a == l or b == l:
        return True
    else:
        return False
    
def new_count_check(pass_list):
    count = 0
    for line in pass_list:
        amount, l, password = line.split()
        if new_pass_check(amount, l[0], password):
            count += 1
    return count